-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 21:37:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dulceria_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dulceria_1` ;

-- -----------------------------------------------------
-- Schema dulceria_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dulceria_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dulceria_1` ;

-- -----------------------------------------------------
-- Table `dulceria_1`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`categoria` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`categoria` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`cliente` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nom_Cliente` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`trabajador` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`trabajador` (
  `id_Trab` INT NOT NULL AUTO_INCREMENT,
  `nombre_Trab` VARCHAR(20) NULL DEFAULT NULL,
  `puesto_Trab` VARCHAR(15) NULL DEFAULT NULL,
  `sueldo` DECIMAL(8,2) NULL DEFAULT NULL,
  `venta_semanal` DECIMAL(8,2) NULL DEFAULT NULL,
  `comision` DECIMAL(8,2) GENERATED ALWAYS AS ((case when (`puesto_Trab` = _utf8mb4'Vendedor') then (`venta_semanal` * 0.10) else 0 end)) STORED,
  PRIMARY KEY (`id_Trab`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`ventas` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`ventas` (
  `id_Venta` INT NOT NULL AUTO_INCREMENT,
  `id_Cliente` INT NULL DEFAULT NULL,
  `id_Trab` INT NULL DEFAULT NULL,
  `total_Venta` DECIMAL(8,2) NULL DEFAULT NULL,
  `fecha_Venta` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_Venta`),
  INDEX `id_Cliente` (`id_Cliente` ASC) VISIBLE,
  INDEX `id_Trab` (`id_Trab` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `dulceria_1`.`cliente` (`id_Cliente`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`id_Trab`)
    REFERENCES `dulceria_1`.`trabajador` (`id_Trab`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`PROVEEDOR` (
  `id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `minicipio` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(5) NULL,
  `fecha_registro` DATETIME NULL,
  `cant_Compra` DECIMAL(5,0) NULL,
  PRIMARY KEY (`id_Proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`producto` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`producto` (
  `id_Prod` INT NOT NULL AUTO_INCREMENT,
  `nombre_Prod` VARCHAR(20) NOT NULL,
  `id_Prov` INT NOT NULL,
  `precio_Compra` DECIMAL(8,2) NOT NULL,
  `precio_Venta` DECIMAL(8,2) NOT NULL,
  `id_Categoria` INT NOT NULL,
  `stock_Disp` DECIMAL(5,0) NOT NULL,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Prod`),
  INDEX `id_Prov` (`id_Prov` ASC) VISIBLE,
  INDEX `id_Categoria` (`id_Categoria` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_Prov`)
    REFERENCES `dulceria_1`.`PROVEEDOR` (`id_Proveedor`),
  CONSTRAINT `producto_ibfk_2`
    FOREIGN KEY (`id_Categoria`)
    REFERENCES `dulceria_1`.`categoria` (`id_Categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`detalle_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`detalle_ventas` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`detalle_ventas` (
  `id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `id_Venta` INT NOT NULL,
  `id_Prod` INT NOT NULL,
  `cantidad_Prod` INT NOT NULL,
  `precio_Venta` DECIMAL(8,2) NOT NULL,
  `total_Venta` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id_Detalle`),
  INDEX `id_Venta` (`id_Venta` ASC) VISIBLE,
  INDEX `id_Prod` (`id_Prod` ASC) VISIBLE,
  CONSTRAINT `detalle_ventas_ibfk_1`
    FOREIGN KEY (`id_Venta`)
    REFERENCES `dulceria_1`.`ventas` (`id_Venta`),
  CONSTRAINT `detalle_ventas_ibfk_2`
    FOREIGN KEY (`id_Prod`)
    REFERENCES `dulceria_1`.`producto` (`id_Prod`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
