-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 10:41:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dulceria_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dulceria_1` ;

-- -----------------------------------------------------
-- Schema dulceria_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dulceria_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dulceria_1` ;

-- -----------------------------------------------------
-- Table `dulceria_1`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`CATEGORIA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`PROVEEDOR` (
  `id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `municipality` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `date_register` DATETIME NULL,
  PRIMARY KEY (`id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`PRODUCTO` (
  `idPRODUCTO` DECIMAL(5,0) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL,
  `price_buys` DECIMAL(4,2) NULL DEFAULT NULL,
  `price_sale` DECIMAL(4,2) NULL DEFAULT NULL,
  `stock` INT NULL,
  `CATEGORIA_id_categoria` INT NOT NULL,
  `PROVEEDOR_id_Proveedor` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTO`),
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORIA_id_categoria` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_id_Proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_categoria`)
    REFERENCES `dulceria_1`.`CATEGORIA` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_Proveedor`)
    REFERENCES `dulceria_1`.`PROVEEDOR` (`id_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`TRABAJADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`TRABAJADOR` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`TRABAJADOR` (
  `id_trab` DECIMAL(5,0) NOT NULL,
  `nom_trab` VARCHAR(20) NOT NULL,
  `puesto_trab` VARCHAR(15) NULL DEFAULT NULL,
  `sueldo` DECIMAL(6,2) NULL DEFAULT NULL,
  `venta_semanal` DECIMAL(6,2) NULL DEFAULT NULL,
  `comis` DECIMAL(6,2) NULL DEFAULT NULL,
  `date_register` DATETIME NULL,
  PRIMARY KEY (`id_trab`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria_1`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dulceria_1`.`VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`VENTAS` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`VENTAS` (
  `idVENTAS` INT NOT NULL,
  `total_sale` DECIMAL(4,2) NULL,
  `date_sale` VARCHAR(45) NULL,
  `payment_method` VARCHAR(45) NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  PRIMARY KEY (`idVENTAS`),
  INDEX `fk_VENTAS_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `dulceria_1`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dulceria_1`.`DETALLE_VENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria_1`.`DETALLE_VENTA` ;

CREATE TABLE IF NOT EXISTS `dulceria_1`.`DETALLE_VENTA` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `PRODUCTO_idPRODUCTO` DECIMAL(5,0) NOT NULL,
  `VENTAS_idVENTAS` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `unit_price` DECIMAL(4,2) NULL,
  `subtotal` DECIMAL(4,2) NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_PRODUCTO_has_VENTAS1_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC) VISIBLE,
  INDEX `fk_DETALLE_VENTA_VENTAS1_idx` (`VENTAS_idVENTAS` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_VENTAS1_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO`)
    REFERENCES `dulceria_1`.`PRODUCTO` (`idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_VENTA_VENTAS1`
    FOREIGN KEY (`VENTAS_idVENTAS`)
    REFERENCES `dulceria_1`.`VENTAS` (`idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
