-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 09:32:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Dulceria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Dulceria` ;

-- -----------------------------------------------------
-- Schema Dulceria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dulceria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Dulceria` ;

-- -----------------------------------------------------
-- Table `Dulceria`.`CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`CATEGORIA` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`PROVEEDOR` (
  `id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `minicipio` VARCHAR(45) NULL DEFAULT NULL,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(5) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_Proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`CLIENTE` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nom_Cliente` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`PRODUCTO` (
  `id_Prod` INT NOT NULL AUTO_INCREMENT,
  `nombre_Prod` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `stock_Disp` INT NOT NULL,
  `disponibilidad` TINYINT GENERATED ALWAYS AS ((CASE WHEN (stock_Disp > 0) THEN 1 ELSE 0 END)),
  `precio_Compra` DECIMAL(8,2) NOT NULL,
  `precio_Venta` DECIMAL(8,2) NOT NULL,
  `PROVEEDOR_id_Proveedor` INT NOT NULL,
  `CATEGORIA_id_Categoria` INT NOT NULL,
  PRIMARY KEY (`id_Prod`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_id_Proveedor` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_CATEGORIA1_idx` (`CATEGORIA_id_Categoria` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_id_Proveedor`)
    REFERENCES `Dulceria`.`PROVEEDOR` (`id_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id_Categoria`)
    REFERENCES `Dulceria`.`CATEGORIA` (`id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`EMPLEADO` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `rfc` VARCHAR(15) NULL,
  `puesto` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `sueldo` DECIMAL(8,2) NULL DEFAULT NULL,
  `venta_semanal` DECIMAL(8,2) NULL DEFAULT NULL,
  `comision` DECIMAL(8,2) GENERATED ALWAYS AS ((case when (`puesto` = _utf8mb4'VENDEDOR') then (`venta_semanal` * 0.10) else 0 end)) STORED,
  `fecha_registro` DATETIME NOT NULL,
  `fecha_baja` DATETIME NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`VENTAS` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`VENTAS` (
  `id_Venta` INT NOT NULL AUTO_INCREMENT,
  `total_Venta` DECIMAL(8,2) NULL DEFAULT NULL,
  `fecha_Venta` DATETIME NULL DEFAULT NULL,
  `CLIENTE_id_Cliente` INT NOT NULL,
  `EMPLEADO_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`id_Venta`),
  INDEX `fk_ventas_CLIENTE1_idx` (`CLIENTE_id_Cliente` ASC) VISIBLE,
  INDEX `fk_VENTAS_EMPLEADO1_idx` (`EMPLEADO_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_CLIENTE1`
    FOREIGN KEY (`CLIENTE_id_Cliente`)
    REFERENCES `Dulceria`.`CLIENTE` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_idEmpleado`)
    REFERENCES `Dulceria`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Dulceria`.`DETALLE_VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dulceria`.`DETALLE_VENTAS` ;

CREATE TABLE IF NOT EXISTS `Dulceria`.`DETALLE_VENTAS` (
  `id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad_Prod` INT NOT NULL,
  `precio_Venta` DECIMAL(8,2) NOT NULL,
  `total_Venta` DECIMAL(8,2) NOT NULL,
  `PRODUCTO_id_Prod` INT NOT NULL,
  `VENTAS_id_Venta` INT NOT NULL,
  PRIMARY KEY (`id_Detalle`),
  INDEX `fk_detalle_ventas_PRODUCTO1_idx` (`PRODUCTO_id_Prod` ASC) VISIBLE,
  INDEX `fk_DETALLE_VENTAS_VENTAS1_idx` (`VENTAS_id_Venta` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_ventas_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_Prod`)
    REFERENCES `Dulceria`.`PRODUCTO` (`id_Prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_VENTAS_VENTAS1`
    FOREIGN KEY (`VENTAS_id_Venta`)
    REFERENCES `Dulceria`.`VENTAS` (`id_Venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
